version: '3.8'

services:
  postgres:
    build:
      context: .
      dockerfile: Dockerfiles/postgres.Dockerfile
    container_name: postgres_container
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: DBR
    ports:
      - "5432:5432"
    networks:
      - db-network

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - db-network

  mongo:
    build:
      context: .
      dockerfile: Dockerfiles/mongo.Dockerfile
    container_name: mongo_container
    ports:
      - "27017:27017"
    networks:
      - db-network

  cassandra:
    build:
      context: .
      dockerfile: Dockerfiles/cassandra.Dockerfile
    container_name: cassandra_container 
    ports:
      - "9042:9042"
    networks:
      - db-network
    environment:
      - CASSANDRA_START_RPC=true

  python-script:
    build:
      context: .
      dockerfile: Dockerfiles/python.Dockerfile
    container_name: python_script_container
    volumes:
      - ./data:/app/data
    depends_on:
      - mongo
    networks:
      - db-network

networks:
  db-network:
    driver: bridge